apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: PR_NAMESPACE
  labels:
    app: sample-app
    pr-number: "PR_NUMBER"
spec:
  type: NodePort
  selector:
    app: sample-app
    pr-number: "PR_NUMBER"
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: NODE_PORT
    protocol: TCP
    name: http
